# Define language servers for Helix

# === Rust ===
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

# === Python ===
[[language]]
name = "python"
language-servers = ["pyright"]

# === Go ===
[[language]]
name = "go"
roots = ["go.mod", "go.work"]
auto-format = true
indent = { tab-width = 4, unit = "    " }
comment-token = "//"
language-servers = ["gopls"]
formatter = { command = "goimports" }
