music_directory "$HOME/Music"
playlist_directory "$HOME/.mpd/playlists"
db_file "$HOME/.mpd/database"
state_file "$HOME/.mpd/state"
sticker_file "$HOME/.mpd/sticker.sql"
bind_to_address "$HOME/.mpd/socket"

audio_buffer_size  "8192"
buffer_before_play "50%"

audio_output {
    type "sndio"
    name "sndio"
    buffer_time "2000"
}

audio_output {
    type "fifo"
    name "my_fifo"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}